import type { Metadata, Viewport } from "next";
import { Inter, Fraunces, Playfair_Display, Lora, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { PWARegister } from "@/components/PWARegister";

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["500", "600"],
});

const playfair = Playfair_Display({
  variable: "--font-display-serif",
  subsets: ["latin"],
  weight: ["500", "600"],
});

const lora = Lora({
  variable: "--font-body-serif",
  subsets: ["latin"],
});

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata: Metadata = {
  title: "Buildmy CV — free CV builder",
  description: "Build and export a polished CV in minutes. No account, no server — everything stays in your browser.",
  // Manifest is generated by src/app/manifest.ts and auto-linked by Next
  // with the correct basePath. Icons use relative paths so they resolve
  // whether the app is hosted at a domain root or a GitHub Pages subpath.
  icons: { icon: "icon.svg", apple: "icon-512.svg" },
};

export const viewport: Viewport = {
  themeColor: "#1B2430",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${fraunces.variable} ${playfair.variable} ${lora.variable} ${grotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        {children}
        <PWARegister />
      </body>
    </html>
  );
}
